CREATE TABLE Z_OPERADOR (
ID_OPERADOR NUMBER (7) NOT NULL,
NOMBRE VARCHAR2 (25) NOT NULL,
ROL VARCHAR2 (35) NOT NULL,
CONSTRAINT Z_OPERADOR_PK PRIMARY KEY (ID_OPERADOR));

CREATE TABLE Z_INCIDENCIA_REPORTE (
ID NUMBER (7) NOT NULL,
NOMBRE VARCHAR2 (25) NOT NULL, 
DESCRIPCION VARCHAR2(55) NOT NULL,
ID_OPERADOR_IN NUMBER (7)NOT NULL,
CONSTRAINT Z_INCIDENCIA_REPORTE_PK PRIMARY KEY (ID),
CONSTRAINT Z_INCIDENCIA_REPORTE_FK FOREIGN KEY (ID_OPERADOR_IN) REFERENCES Z_OPERADOR (ID_OPERADOR));

COMMIT;

